"""adicionando coluna creator nas collections

Revision ID: 7fb37baf8cff
Revises: 5d6556fdbf31
Create Date: 2022-05-04 14:54:30.925897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb37baf8cff'
down_revision = '5d6556fdbf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'collections', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'creator')
    # ### end Alembic commands ###
